// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Bio  string    `json:"bio"`
}

type Book struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	DurationSeconds int32              `json:"duration_seconds"`
	Rating          pgtype.Numeric     `json:"rating"`
	ReleaseDate     pgtype.Date        `json:"release_date"`
	CoverImageUrl   string             `json:"cover_image_url"`
	AudioPreviewUrl string             `json:"audio_preview_url"`
	IsAbridged      bool               `json:"is_abridged"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type BookAuthor struct {
	BookID   uuid.UUID `json:"book_id"`
	AuthorID uuid.UUID `json:"author_id"`
}

type BookGenre struct {
	BookID  uuid.UUID `json:"book_id"`
	GenreID uuid.UUID `json:"genre_id"`
}

type BookNarrator struct {
	BookID     uuid.UUID `json:"book_id"`
	NarratorID uuid.UUID `json:"narrator_id"`
}

type Chapter struct {
	ID         uuid.UUID `json:"id"`
	BookID     uuid.UUID `json:"book_id"`
	Title      string    `json:"title"`
	StartTime  int32     `json:"start_time"`
	EndTime    int32     `json:"end_time"`
	OrderIndex int32     `json:"order_index"`
}

type Genre struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Narrator struct {
	ID   uuid.UUID   `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}
