// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"

	"github.com/google/uuid"
)

type Author struct {
	ID   uuid.UUID
	Name string
	Bio  string
}

type Book struct {
	ID              uuid.UUID
	Title           string
	DurationSeconds int32
	Rating          float64
	ReleaseDate     time.Time
	CoverImageUrl   string
	AudioPreviewUrl string
	IsAbridged      bool
	CreatedAt       time.Time
}

type BookAuthor struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
}

type BookGenre struct {
	BookID  uuid.UUID
	GenreID uuid.UUID
}

type BookNarrator struct {
	BookID     uuid.UUID
	NarratorID uuid.UUID
}

type Chapter struct {
	ID         uuid.UUID
	BookID     uuid.UUID
	Title      string
	StartTime  int32
	EndTime    int32
	OrderIndex int32
}

type Genre struct {
	ID   uuid.UUID
	Name string
}

type Narrator struct {
	ID   uuid.UUID
	Name string
	Bio  *string
}
