// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAuthorToBook = `-- name: AddAuthorToBook :exec
INSERT INTO book_authors (book_id, author_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddAuthorToBookParams struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) AddAuthorToBook(ctx context.Context, arg AddAuthorToBookParams) error {
	_, err := q.db.Exec(ctx, addAuthorToBook, arg.BookID, arg.AuthorID)
	return err
}

const addGenreToBook = `-- name: AddGenreToBook :exec
INSERT INTO book_genres (book_id, genre_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddGenreToBookParams struct {
	BookID  uuid.UUID
	GenreID uuid.UUID
}

func (q *Queries) AddGenreToBook(ctx context.Context, arg AddGenreToBookParams) error {
	_, err := q.db.Exec(ctx, addGenreToBook, arg.BookID, arg.GenreID)
	return err
}

const addNarratorToBook = `-- name: AddNarratorToBook :exec
INSERT INTO book_narrators (book_id, narrator_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddNarratorToBookParams struct {
	BookID     uuid.UUID
	NarratorID uuid.UUID
}

func (q *Queries) AddNarratorToBook(ctx context.Context, arg AddNarratorToBookParams) error {
	_, err := q.db.Exec(ctx, addNarratorToBook, arg.BookID, arg.NarratorID)
	return err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio)
VALUES ($1, $2)
RETURNING id, name, bio
`

type CreateAuthorParams struct {
	Name string
	Bio  string
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const createBook = `-- name: CreateBook :one

INSERT INTO books (
    title,
    duration_seconds,
    rating,
    release_date,
    cover_image_url,
    audio_preview_url,
    is_abridged
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, title, duration_seconds, rating, release_date, cover_image_url, audio_preview_url, is_abridged, created_at
`

type CreateBookParams struct {
	Title           string
	DurationSeconds int32
	Rating          float64
	ReleaseDate     time.Time
	CoverImageUrl   string
	AudioPreviewUrl string
	IsAbridged      bool
}

// -----------------------------------------------------------------------------------------------------
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.DurationSeconds,
		arg.Rating,
		arg.ReleaseDate,
		arg.CoverImageUrl,
		arg.AudioPreviewUrl,
		arg.IsAbridged,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DurationSeconds,
		&i.Rating,
		&i.ReleaseDate,
		&i.CoverImageUrl,
		&i.AudioPreviewUrl,
		&i.IsAbridged,
		&i.CreatedAt,
	)
	return i, err
}

const createChapter = `-- name: CreateChapter :one

INSERT INTO chapters (book_id, title, start_time, end_time, order_index)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, book_id, title, start_time, end_time, order_index
`

type CreateChapterParams struct {
	BookID     uuid.UUID
	Title      string
	StartTime  int32
	EndTime    int32
	OrderIndex int32
}

// -----------------------------------------------------------------------------------------------------
func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, createChapter,
		arg.BookID,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.OrderIndex,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.OrderIndex,
	)
	return i, err
}

const createGenre = `-- name: CreateGenre :one

INSERT INTO genres (name) VALUES ($1) RETURNING id, name
`

// -----------------------------------------------------------------------------------------------------
func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createNarrator = `-- name: CreateNarrator :one

INSERT INTO narrators (name, bio)
VALUES ($1, $2)
RETURNING id, name, bio
`

type CreateNarratorParams struct {
	Name string
	Bio  *string
}

// -----------------------------------------------------------------------------------------------------
func (q *Queries) CreateNarrator(ctx context.Context, arg CreateNarratorParams) (Narrator, error) {
	row := q.db.QueryRow(ctx, createNarrator, arg.Name, arg.Bio)
	var i Narrator
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const deleteChapter = `-- name: DeleteChapter :exec
DELETE FROM chapters WHERE id = $1
`

func (q *Queries) DeleteChapter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChapter, id)
	return err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genres WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGenre, id)
	return err
}

const deleteNarrator = `-- name: DeleteNarrator :exec
DELETE FROM narrators WHERE id = $1
`

func (q *Queries) DeleteNarrator(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNarrator, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio FROM authors WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT
    b.id, b.title, b.duration_seconds, b.rating, b.release_date, b.cover_image_url, b.audio_preview_url, b.is_abridged, b.created_at,
    array_agg(DISTINCT a.name)::text[] as authors,
    array_agg(DISTINCT n.name)::text[] as narrators
FROM books b
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
LEFT JOIN book_narrators bn ON b.id = bn.book_id
LEFT JOIN narrators n ON bn.narrator_id = n.id
WHERE b.id = $1
GROUP BY b.id
LIMIT 1
`

type GetBookRow struct {
	ID              uuid.UUID
	Title           string
	DurationSeconds int32
	Rating          float64
	ReleaseDate     time.Time
	CoverImageUrl   string
	AudioPreviewUrl string
	IsAbridged      bool
	CreatedAt       time.Time
	Authors         []string
	Narrators       []string
}

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (GetBookRow, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i GetBookRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DurationSeconds,
		&i.Rating,
		&i.ReleaseDate,
		&i.CoverImageUrl,
		&i.AudioPreviewUrl,
		&i.IsAbridged,
		&i.CreatedAt,
		&i.Authors,
		&i.Narrators,
	)
	return i, err
}

const getGenre = `-- name: GetGenre :one
SELECT id, name FROM genres WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGenre(ctx context.Context, id uuid.UUID) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenresForBook = `-- name: GetGenresForBook :many
SELECT g.id, g.name FROM genres g
JOIN book_genres bg ON g.id = bg.genre_id
WHERE bg.book_id = $1
`

func (q *Queries) GetGenresForBook(ctx context.Context, id uuid.UUID) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getGenresForBook, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNarrator = `-- name: GetNarrator :one
SELECT id, name, bio FROM narrators WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNarrator(ctx context.Context, id uuid.UUID) (Narrator, error) {
	row := q.db.QueryRow(ctx, getNarrator, id)
	var i Narrator
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio FROM authors ORDER BY name
`

func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT
    b.id,
    b.title,
    b.release_date,
    b.cover_image_url,
    b.rating,
    array_agg(DISTINCT a.name)::text[] as authors
FROM books b
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
GROUP BY b.id
ORDER BY b.release_date DESC
`

type ListBooksRow struct {
	ID            uuid.UUID
	Title         string
	ReleaseDate   time.Time
	CoverImageUrl string
	Rating        float64
	Authors       []string
}

func (q *Queries) ListBooks(ctx context.Context) ([]ListBooksRow, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseDate,
			&i.CoverImageUrl,
			&i.Rating,
			&i.Authors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersByBook = `-- name: ListChaptersByBook :many
SELECT id, book_id, title, start_time, end_time, order_index FROM chapters
WHERE book_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListChaptersByBook(ctx context.Context, bookID uuid.UUID) ([]Chapter, error) {
	rows, err := q.db.Query(ctx, listChaptersByBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chapter
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many
SELECT id, name FROM genres ORDER BY name
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNarrators = `-- name: ListNarrators :many
SELECT id, name, bio FROM narrators ORDER BY name
`

func (q *Queries) ListNarrators(ctx context.Context) ([]Narrator, error) {
	rows, err := q.db.Query(ctx, listNarrators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Narrator
	for rows.Next() {
		var i Narrator
		if err := rows.Scan(&i.ID, &i.Name, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAuthorFromBook = `-- name: RemoveAuthorFromBook :exec
DELETE FROM book_authors
WHERE book_id = $1 AND author_id = $2
`

type RemoveAuthorFromBookParams struct {
	BookID   uuid.UUID
	AuthorID uuid.UUID
}

func (q *Queries) RemoveAuthorFromBook(ctx context.Context, arg RemoveAuthorFromBookParams) error {
	_, err := q.db.Exec(ctx, removeAuthorFromBook, arg.BookID, arg.AuthorID)
	return err
}

const removeGenreFromBook = `-- name: RemoveGenreFromBook :exec
DELETE FROM book_genres
WHERE book_id = $1 AND genre_id = $2
`

type RemoveGenreFromBookParams struct {
	BookID  uuid.UUID
	GenreID uuid.UUID
}

func (q *Queries) RemoveGenreFromBook(ctx context.Context, arg RemoveGenreFromBookParams) error {
	_, err := q.db.Exec(ctx, removeGenreFromBook, arg.BookID, arg.GenreID)
	return err
}

const removeNarratorFromBook = `-- name: RemoveNarratorFromBook :exec
DELETE FROM book_narrators
WHERE book_id = $1 AND narrator_id = $2
`

type RemoveNarratorFromBookParams struct {
	BookID     uuid.UUID
	NarratorID uuid.UUID
}

func (q *Queries) RemoveNarratorFromBook(ctx context.Context, arg RemoveNarratorFromBookParams) error {
	_, err := q.db.Exec(ctx, removeNarratorFromBook, arg.BookID, arg.NarratorID)
	return err
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET name = $1, bio = $2
WHERE id = $3
RETURNING id, name, bio
`

type UpdateAuthorParams struct {
	Name string
	Bio  string
	ID   uuid.UUID
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor, arg.Name, arg.Bio, arg.ID)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET
    title           = $1,
    rating          = $2,
    is_abridged     = $3
WHERE id = $4
RETURNING id, title, duration_seconds, rating, release_date, cover_image_url, audio_preview_url, is_abridged, created_at
`

type UpdateBookParams struct {
	Title      string
	Rating     float64
	IsAbridged bool
	ID         uuid.UUID
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.Title,
		arg.Rating,
		arg.IsAbridged,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DurationSeconds,
		&i.Rating,
		&i.ReleaseDate,
		&i.CoverImageUrl,
		&i.AudioPreviewUrl,
		&i.IsAbridged,
		&i.CreatedAt,
	)
	return i, err
}

const updateChapter = `-- name: UpdateChapter :one
UPDATE chapters
SET
    title      = $1,
    start_time = $2,
    end_time   = $3,
    order_index = $4
WHERE id = $5
RETURNING id, book_id, title, start_time, end_time, order_index
`

type UpdateChapterParams struct {
	Title      string
	StartTime  int32
	EndTime    int32
	OrderIndex int32
	ID         uuid.UUID
}

func (q *Queries) UpdateChapter(ctx context.Context, arg UpdateChapterParams) (Chapter, error) {
	row := q.db.QueryRow(ctx, updateChapter,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.OrderIndex,
		arg.ID,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.OrderIndex,
	)
	return i, err
}

const updateNarrator = `-- name: UpdateNarrator :one
UPDATE narrators
SET name = $1, bio = $2
WHERE id = $3
RETURNING id, name, bio
`

type UpdateNarratorParams struct {
	Name string
	Bio  *string
	ID   uuid.UUID
}

func (q *Queries) UpdateNarrator(ctx context.Context, arg UpdateNarratorParams) (Narrator, error) {
	row := q.db.QueryRow(ctx, updateNarrator, arg.Name, arg.Bio, arg.ID)
	var i Narrator
	err := row.Scan(&i.ID, &i.Name, &i.Bio)
	return i, err
}
